spring:
  kafka:
    bootstrap-servers: 13.125.45.117:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer