spring:
  kafka:
    bootstrap-servers:
      - 15.164.165.136:9092
      - 15.164.165.136:19092
      - 15.164.165.136:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        partitioner.class: org.apache.kafka.clients.producer.RoundRobinPartitioner