server:
  port: 0

spring:
  kafka:
    bootstrap-servers:
      - 15.164.165.136:9092
      - 15.164.165.136:19092
      - 15.164.165.136:29092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest